# Generated by Django 4.2.4 on 2023-10-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
